
export const LEGEND_CHANGE = "LEGEND_CHANGE";
export const GRID_INITIAL = "GRID_INITIAL";
export const CHART_INIT = "CHART_INIT";
export const FORM_QUERY_ARGS = 'PLATFORM/REPORTS/FORM_QUERY_ARGS'; //获取查询参数列表
